name: Lint & Dependency Audit

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: lint-audit-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint_audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11", "3.12" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff black pip-audit

      # ---- Linting & formatting checks ----
      - name: Ruff (lint)
        run: ruff check .

      - name: Black (format check)
        run: black --check .

      # ---- Dependency vulnerability audit ----
      - name: Pip-audit (requirements.txt)
        run: pip-audit -r requirements.txt
